# .github/workflows/dotnet-build.yml
name: Build and Publish SmartParser

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      publish-release:
        type: boolean
        description: 'Publish Release'
        required: false
        default: false
      version:
        description: 'Version'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.sln') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore Smart.Parser.sln

      - name: Build the project
        run: dotnet build Smart.Parser.sln --configuration Release --no-restore

#      - name: Run Unit Tests
#        run: dotnet test Smart.Parser.sln --configuration Release --no-build --verbosity normal

      - name: Publish the project
        run: dotnet publish src/Smart.Parser.csproj --configuration Release --no-build --output ./published

      - name: Compress published files
        run: |
          mkdir artifacts
          zip -r artifacts/smart-parser.zip ./published
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: smart-parser
          path: artifacts/smart-parser.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ inputs.publish-release }}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: smart-parser
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.version }}
          name: Smart Parser v${{ inputs.version }}
          files: artifacts/smart-parser.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
