# .github/workflows/dotnet-build.yml
name: Build and Publish SmartParser

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.sln') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
      - name: Restore dependencies
        run: dotnet restore Smart.Parser.sln

      - name: Build the project
        run: dotnet build Smart.Parser.sln --configuration Release

      - name: Run Unit Tests
        run: dotnet test Smart.Parser.sln --configuration Release --no-build --verbosity normal

      - name: Publish the project
        run: dotnet publish src/Smart.Parser.csproj --configuration Release --output ./published

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: smart-parser-release
          path: ./published
